# Generated by Django 2.2.5 on 2019-12-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
