# Generated by Django 2.2.5 on 2019-12-20 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None), null=True, size=None),
        ),
    ]
